name: 'Slack V2 Upload'
description: 'Upload File to Slack'
author: 'Dmytro Onypko <vaporif@gmail.com>'

branding:
  icon: 'upload'
  color: 'white'

inputs:
  path:
    description: 'Path to file'
    required: true
  token:
    description: 'Slack token'
    required: true
  channel_id:
    description: 'Slack channel_id'
    required: false
  thread_ts:
    description: 'Slack thread_ts'
    required: false
  filename:
    description: 'Filename of a file'
    required: false
  initial_comment:
    description: 'Message text introducing file in channels'
    required: false
  title:
    description: 'File title'
    required: false
outputs:
  result:
    description: 'response from slack'

runs:
  using: node20
  main: dist/index.js
