name: 'Slack V2 Upload'
description: 'Upload File to Slack'
author: 'Dmytro Onypko <vaporif@gmail.com>'

branding:
  icon: 'upload'
  color: 'white'

inputs:
  token:
    description: 'Slack token'
    required: true
  files:
    description: 'List of files including file path and filename'
    default: '[]'
    required: true
  channel_id:
    description: 'Slack channel_id'
    required: false
  thread_ts:
    description: 'Slack thread_ts'
    required: false
  initial_comment:
    description: 'Message with file post'
    required: false
  title:
    description: 'Title'
    required: false
outputs:
  result:
    description: 'response from slack'

runs:
  using: node20
  main: dist/index.js
