name: 'Slack V2 Upload'
description: 'Upload File to Slack'
author: 'Dmytro Onypko <vaporif@gmail.com>'

branding:
  icon: 'upload'
  color: 'white'

inputs:
  path:
    description: 'Path to file'
    required: true
  token:
    description: 'Slack token'
    required: true
  channel:
    description: 'Slack channels'
    required: false
  thread_ts:
    description: 'Slack thread_ts'
    required: false
  filename:
    description: 'Filename of file'
    required: false
  initial_comment:
    description: 'The message text introducing the file in specified channels'
    required: false

outputs:
  result:
    description: 'response from slack'

runs:
  using: node20
  main: dist/index.js
